const actionTypes = {
  // ROUTE TYPES
  SET_BEGIN_ROUTE: 'SET_BEGIN_ROUTE',
  SET_CURRENT_LOCATION: 'SET_CURRENT_LOCATION',
  SET_CURRENT_OPERATION: 'SET_CURRENT_OPERATION',
  REPLACE_OUTDATED_OPERATION: 'REPLACE_OUTDATED_OPERATION',
  REPLACE_OUTDATED_LOCATION: 'REPLACE_OUTDATED_LOCATION',
  // UNSENT LOCATIONS TYPES
  REMOVE_FROM_UNSENT_LOC: 'REMOVE_FROM_UNSENT_LOC',
  ADD_TO_UNSENT_LOCATIONS: 'ADD_TO_UNSENT_LOCATIONS',

  // AUTH_TYPES
  SET_END_ROUTE: 'SET_END_ROUTE',
  SET_CURRENT_PERSONNEL_TO_SCAN: 'SET_CURRENT_PERSONNEL_TO_SCAN',
  SET_OPEN_AUTH_SCREEN: 'SET_OPEN_AUTH_SCREEN',
  // LOADING_TYPES
  SET_LOADING: 'SET_LOADING',
  SET_LOADING_TEXT: 'SET_LOADING_TEXT',
  // SETTING_TYPES
  SET_DARK_MODE: 'SET_DARK_MODE',
  SET_CAMERA_SOUND: 'SET_CAMERA_SOUND',
  SET_AUTH_CODES: 'SET_AUTH_CODES',
  SET_PRINT_COPIES: 'SET_PRINT_COPIES',
  SET_VIBRATE_ON_SCAN: 'SET_VIBRATE_ON_SCAN',
  SET_SOUND: 'SET_SOUND',
  SET_SHOW_SCREEN_NAMES: 'SET_SHOW_SCREEN_NAMES',
  SET_SKIP_AUTH: 'SET_SKIP_AUTH',
};

export default actionTypes;
